- hosts : localhost
  become : true
  pre_tasks : 
    - name : Update cache
      apt : 
        update_cache : yes
      tags : 
        - nodejs
        - zsh
  tasks : 
    - include_tasks : ansible_file/zsh.yml
    - include_tasks : ansible_file/node.yml